{% set version = "0.2.0" %}

package:
  name: stim
  version: {{ version }}

source:
  url: https://github.com/PreibischLab/STIM/archive/refs/tags/v0.2.0.zip
  sha256: b09f72c33efd87f0251e00e8f70cba33c94f4857538e0d2b70d8aa3b3632f297

build:
  number: 0

requirements:
  build:
    - openjdk
    - maven
  run:
    - openjdk

test:
  commands:
    - st-help --version

about:
  home: https://github.com/PreibischLab/STIM
  summary: 'STIM - the Spatial Transcriptomics ImgLib2/Imaging Project'
  description: |
    STIM is a framework for managing, storage, viewing, and processing spatial
    transcriptomics data, which builds on the powerful libraries Imglib2, N5,
    BigDataViewer and Fiji.
  license: GPL-3.0-or-later
  license_file: license

extra:
  recipe-maintainers:
    - minnerbe
    - StephanPreibisch
