{% set version = "0.1.0" %}

package:
  name: stim
  version: {{ version }}

source:
  # uncomment the line below, and modify as needed. Use releases if available:
  # url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  # and otherwise fall back to archive:
  # https://github.com/simplejson/simplejson/archive/v{{ version }}.tar.gz
  url: https://github.com/PreibischLab/STIM/archive/refs/heads/master.zip
  sha256: 2f90489ee53ede68d2d0ef451d125cc01d57f8392c505f733ca658d8a4e05d96

build:
  number: 0

requirements:
  build:
    - openjdk
    - mvn
  run:
    - openjdk

test:
  commands:
    - ls -1 st-*

about:
  home: https://github.com/PreibischLab/STIM
  summary: 'STIM - the Spatial Transcriptomics ImgLib2/Imaging Project'
  description: |
    STIM is a framework for managing, storage, viewing, and processing spatial
    transcriptomics data, which builds on the powerful libraries Imglib2, N5,
    BigDataViewer and Fiji.
  license: GPL-3.0-or-later
  license_file: license

extra:
  recipe-maintainers:
    - minnerbe
    - StephanPreibisch
