{% set version = "0.2.0" %}

package:
  name: stim
  version: {{ version }}

source:
  url: https://github.com/PreibischLab/STIM/archive/refs/tags/v0.3.0-alpha.zip
  sha256: 0827c60deb6af9021ab7f08e0a23f9dd2d0aee3df7f2ccb075022dad31b8471d

build:
  number: 0

requirements:
  build:
    - maven
  host:
    - openjdk
  run:
    - blosc

test:
  commands:
    - st-help --version

about:
  home: https://github.com/PreibischLab/STIM
  summary: 'STIM - the Spatial Transcriptomics ImgLib2/Imaging Project'
  description: |
    STIM is a framework for managing, storage, viewing, and processing spatial
    transcriptomics data, which builds on the powerful libraries Imglib2, N5,
    BigDataViewer and Fiji.
  license: GPL-3.0-or-later
  license_file: license

extra:
  recipe-maintainers:
    - minnerbe
    - StephanPreibisch
